site_name: KendirStudios Documentation Page
site_url: https://kendirstudio.github.io/KendirStudios-DeveloperDocumentation/
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/Logo_white.png
  favicon: assets/Logo_white.png
  palette:
  # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: var(--md-primary-fg-color)
      accent: var(--md-accent-fg-color)
    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: var(--md-primary-fg-color)
      accent: var(--md-accent-fg-color)
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - content.code.line_numbers
    - search.suggest
    - search.highlight
    
nav: 
  - Home: index.md
  - Custom Packages: 
    - How to install: custom-packages/how-to-install.md
    - Internal Packages: custom-packages/internal-packages.md
    - External Packages: custom-packages/external-packages.md
  - Resources:
    - How to Access: resources/resources-home.md
    - Game Development Assets: resources/assets/game-development-assets.md
    - Art:
      - Articles: resources/art/art-articles.md
      - EBooks: resources/art/art-ebooks.md
      - Tools: resources/art/art-tools.md
      - Youtube: resources/art/art-youtube.md
    - Programming:
      - Articles: resources/programming/programming-articles.md
      - Courses: resources/programming/programming-courses.md
      - EBooks: resources/programming/programming-ebooks.md
      - Youtube: resources/programming/programming-youtube.md
    - Game Design:
      - Youtube: resources/game-design/game-design-youtube.md
  - Training:
    - Programming:
      - Code Structure: training/programming/code-structure.md
      
  - MK Docs: mkdocs.md