site_name: KendirStudios Developer Documentation

theme:
  name: material
  palette:
  # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: green
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: green
      accent: deep purple
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - content.code.line_numbers
    - search.suggest
    - search.highlight
    
nav: 
  - MK Docs: index.md
  - Custom Packages: 
    - How to install: custom-packages/how-to-install.md
    - Available Packages: custom-packages/available-packages-urls.md
  - Resources:
    - How to Access: resources/resources-home.md
    - Programming:
      - Articles: resources/programming/programming-articles.md
      - Courses: resources/programming/programming-courses.md
    - Design:
      - Articles: resources/design/design-articles.md
      - VFX: resources/design/design-vfx.md
      - EBooks: resources/design/design-ebooks.md
    - Assets:
      - 3D Models: resources/assets/3d-models.md
      - Music: resources/assets/music.md